-- Rare Disease Atlas: Postgres / Supabase schema (generated by atlas.export; idempotent).
-- Load the matching CSVs with: \copy <table> from '<table>.csv' with (format csv, header true)

create table if not exists public.nodes (
  id text,
  type text not null,
  name text not null,
  synonyms text[],
  attrs jsonb,
  primary key (id)
);
create table if not exists public.edges (
  id text,
  source text not null,
  target text not null,
  relation text not null,
  evidence text,
  confidence numeric,
  polarity text,
  effect text,
  source_name text,
  source_url text,
  quote text,
  context text,
  retrieved_at date,
  submitted_by text,
  frequency text,
  primary key (id)
);
create table if not exists public.coverage (
  disease_id text,
  source text,
  query text,
  n_results integer,
  n_kept integer,
  retrieved_at date,
  primary key (disease_id, source, query)
);
create table if not exists public.similarity (
  a text,
  b text,
  therapeutic numeric,
  phenotype_view numeric,
  gene numeric,
  pathway numeric,
  phenotype numeric,
  lookalike boolean,
  top_witnesses text[],
  primary key (a, b)
);
create table if not exists public.clusters (
  cluster_id integer,
  disease_id text,
  primary key (cluster_id, disease_id)
);
create table if not exists public.journeys (
  disease_id text,
  data jsonb not null,
  primary key (disease_id)
);
create table if not exists public.subgraphs (
  disease_id text,
  data jsonb not null,
  primary key (disease_id)
);
create table if not exists public.emails (
  disease_id text,
  data jsonb not null,
  primary key (disease_id)
);

create index if not exists edges_source_idx on public.edges (source);
create index if not exists edges_target_idx on public.edges (target);
create index if not exists edges_relation_idx on public.edges (relation);
create index if not exists nodes_type_idx on public.nodes (type);

-- Read-only public access: RLS on, one SELECT policy for anon + authenticated, no write policies.
alter table public.nodes enable row level security;
drop policy if exists nodes_read on public.nodes;
create policy nodes_read on public.nodes for select to anon, authenticated using (true);
grant select on public.nodes to anon, authenticated;
alter table public.edges enable row level security;
drop policy if exists edges_read on public.edges;
create policy edges_read on public.edges for select to anon, authenticated using (true);
grant select on public.edges to anon, authenticated;
alter table public.coverage enable row level security;
drop policy if exists coverage_read on public.coverage;
create policy coverage_read on public.coverage for select to anon, authenticated using (true);
grant select on public.coverage to anon, authenticated;
alter table public.similarity enable row level security;
drop policy if exists similarity_read on public.similarity;
create policy similarity_read on public.similarity for select to anon, authenticated using (true);
grant select on public.similarity to anon, authenticated;
alter table public.clusters enable row level security;
drop policy if exists clusters_read on public.clusters;
create policy clusters_read on public.clusters for select to anon, authenticated using (true);
grant select on public.clusters to anon, authenticated;
alter table public.journeys enable row level security;
drop policy if exists journeys_read on public.journeys;
create policy journeys_read on public.journeys for select to anon, authenticated using (true);
grant select on public.journeys to anon, authenticated;
alter table public.subgraphs enable row level security;
drop policy if exists subgraphs_read on public.subgraphs;
create policy subgraphs_read on public.subgraphs for select to anon, authenticated using (true);
grant select on public.subgraphs to anon, authenticated;
alter table public.emails enable row level security;
drop policy if exists emails_read on public.emails;
create policy emails_read on public.emails for select to anon, authenticated using (true);
grant select on public.emails to anon, authenticated;
