/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AmbitionRouteImport } from './routes/ambition'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as ContributeRouteImport } from './routes/contribute'
import { Route as SearchRouteImport } from './routes/search'
import { Route as TeamRouteImport } from './routes/team'
import { Route as WhoRouteImport } from './routes/who'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AtlasIdRouteImport } from './routes/atlas.$id'
import { Route as ChatThreadIdRouteImport } from './routes/chat.$threadId'
import { Route as DiseaseIdRouteImport } from './routes/disease.$id'
import { Route as AtlasMpsIiicAmbitionRouteImport } from './routes/atlas.mps-iiic.ambition'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AmbitionRoute = AmbitionRouteImport.update({
  id: '/ambition',
  path: '/ambition',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ContributeRoute = ContributeRouteImport.update({
  id: '/contribute',
  path: '/contribute',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const WhoRoute = WhoRouteImport.update({
  id: '/who',
  path: '/who',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AtlasIdRoute = AtlasIdRouteImport.update({
  id: '/atlas/$id',
  path: '/atlas/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatThreadIdRoute = ChatThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => ChatRoute,
} as any)
const DiseaseIdRoute = DiseaseIdRouteImport.update({
  id: '/disease/$id',
  path: '/disease/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AtlasMpsIiicAmbitionRoute = AtlasMpsIiicAmbitionRouteImport.update({
  id: '/atlas/mps-iiic/ambition',
  path: '/atlas/mps-iiic/ambition',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ambition': typeof AmbitionRoute
  '/chat': typeof ChatRouteWithChildren
  '/contribute': typeof ContributeRoute
  '/search': typeof SearchRoute
  '/team': typeof TeamRoute
  '/who': typeof WhoRoute
  '/api/chat': typeof ApiChatRoute
  '/atlas/$id': typeof AtlasIdRoute
  '/chat/$threadId': typeof ChatThreadIdRoute
  '/disease/$id': typeof DiseaseIdRoute
  '/atlas/mps-iiic/ambition': typeof AtlasMpsIiicAmbitionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ambition': typeof AmbitionRoute
  '/chat': typeof ChatRouteWithChildren
  '/contribute': typeof ContributeRoute
  '/search': typeof SearchRoute
  '/team': typeof TeamRoute
  '/who': typeof WhoRoute
  '/api/chat': typeof ApiChatRoute
  '/atlas/$id': typeof AtlasIdRoute
  '/chat/$threadId': typeof ChatThreadIdRoute
  '/disease/$id': typeof DiseaseIdRoute
  '/atlas/mps-iiic/ambition': typeof AtlasMpsIiicAmbitionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ambition': typeof AmbitionRoute
  '/chat': typeof ChatRouteWithChildren
  '/contribute': typeof ContributeRoute
  '/search': typeof SearchRoute
  '/team': typeof TeamRoute
  '/who': typeof WhoRoute
  '/api/chat': typeof ApiChatRoute
  '/atlas/$id': typeof AtlasIdRoute
  '/chat/$threadId': typeof ChatThreadIdRoute
  '/disease/$id': typeof DiseaseIdRoute
  '/atlas/mps-iiic/ambition': typeof AtlasMpsIiicAmbitionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ambition'
    | '/chat'
    | '/contribute'
    | '/search'
    | '/team'
    | '/who'
    | '/api/chat'
    | '/atlas/$id'
    | '/chat/$threadId'
    | '/disease/$id'
    | '/atlas/mps-iiic/ambition'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ambition'
    | '/chat'
    | '/contribute'
    | '/search'
    | '/team'
    | '/who'
    | '/api/chat'
    | '/atlas/$id'
    | '/chat/$threadId'
    | '/disease/$id'
    | '/atlas/mps-iiic/ambition'
  id:
    | '__root__'
    | '/'
    | '/ambition'
    | '/chat'
    | '/contribute'
    | '/search'
    | '/team'
    | '/who'
    | '/api/chat'
    | '/atlas/$id'
    | '/chat/$threadId'
    | '/disease/$id'
    | '/atlas/mps-iiic/ambition'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AmbitionRoute: typeof AmbitionRoute
  ChatRoute: typeof ChatRouteWithChildren
  ContributeRoute: typeof ContributeRoute
  SearchRoute: typeof SearchRoute
  TeamRoute: typeof TeamRoute
  WhoRoute: typeof WhoRoute
  ApiChatRoute: typeof ApiChatRoute
  AtlasIdRoute: typeof AtlasIdRoute
  DiseaseIdRoute: typeof DiseaseIdRoute
  AtlasMpsIiicAmbitionRoute: typeof AtlasMpsIiicAmbitionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ambition': {
      id: '/ambition'
      path: '/ambition'
      fullPath: '/ambition'
      preLoaderRoute: typeof AmbitionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contribute': {
      id: '/contribute'
      path: '/contribute'
      fullPath: '/contribute'
      preLoaderRoute: typeof ContributeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/who': {
      id: '/who'
      path: '/who'
      fullPath: '/who'
      preLoaderRoute: typeof WhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atlas/$id': {
      id: '/atlas/$id'
      path: '/atlas/$id'
      fullPath: '/atlas/$id'
      preLoaderRoute: typeof AtlasIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$threadId': {
      id: '/chat/$threadId'
      path: '/$threadId'
      fullPath: '/chat/$threadId'
      preLoaderRoute: typeof ChatThreadIdRouteImport
      parentRoute: typeof ChatRoute
    }
    '/disease/$id': {
      id: '/disease/$id'
      path: '/disease/$id'
      fullPath: '/disease/$id'
      preLoaderRoute: typeof DiseaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atlas/mps-iiic/ambition': {
      id: '/atlas/mps-iiic/ambition'
      path: '/atlas/mps-iiic/ambition'
      fullPath: '/atlas/mps-iiic/ambition'
      preLoaderRoute: typeof AtlasMpsIiicAmbitionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ChatRouteChildren {
  ChatThreadIdRoute: typeof ChatThreadIdRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatThreadIdRoute: ChatThreadIdRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AmbitionRoute: AmbitionRoute,
  ChatRoute: ChatRouteWithChildren,
  ContributeRoute: ContributeRoute,
  SearchRoute: SearchRoute,
  TeamRoute: TeamRoute,
  WhoRoute: WhoRoute,
  ApiChatRoute: ApiChatRoute,
  AtlasIdRoute: AtlasIdRoute,
  DiseaseIdRoute: DiseaseIdRoute,
  AtlasMpsIiicAmbitionRoute: AtlasMpsIiicAmbitionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
